########################
# [FILES]

filename: 'intermediates/suss_with_training.fits'
# A csv or fits file containing the input catalogue
initfilename: ''
# Not used for OM pipeline (all columns in one file)
fileout: 'output/classification_OM.fits'
# The csv or fits file to create, storing the classified catalogue
dirref: 'classif/distrib_KDE_OM/'
# Directory in which are (or will be) stored the probability
# densities (.dat files)

########################
# [PARAM]

save: 1
# Whether to save the classified catalogue as fileout (set to 1 for final run)

record_marginal_pba: 0
# Save the marginal probabilities of each class for all properties used in the classification. Memory intensive.

compute_distrib: 1
# Compute the probability densities of the input catalog thanks
# to its known objects

optimize_coeffs: 0
# Optimize the weighting coeffs of each category of properties
# to maximize of the f1-score of class C
C: -1
# Class on which the classification will be optimized

keep_descriptions: 0
# Not used in OM pipeline

########################
# [DATA_DEPENDENT]

categories: ['brightness', 'colour', 'extent', 'variability']
# Categories of properties; works even when no property is in a
# certain category
global_coeffs: [0.91, 1.52, 6.97, 4.61, 2.07]
# 1 weighting coefficient for missing values (usually 1)
# and then 1 coefficient per category

custom_pty: []
# [Property, Class] for which the probability density is customed,
# to limit bias

classnames: ['Star', 'QSO', 'Galaxy']
# Names of the classes

trueprop: [0.69, 0.13, 0.18]
# Prior proportions of the different classes
